config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :messages do 
  	resources :comments
  end
  root 'messages#index'
 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_message, only: [:create, :edit, :update, :destroy]
    before_action :find_comment, only: [:edit, :update, :destroy]


	def create
		@comment = @message.comments.create(comment_params)
		@comment.user_id = current_user.id
        
        if @comment.save
        	redirect_to message_path(@message)
        else
        	render 'new'
        end
    end

    def edit
    end

    def update
    	if @comment.update(comment_params)
    	  redirect_to message_path(@message)
    	else
    		render 'edit'
    	end
    end

    def destroy
        @comment.destroy
        redirect_to message_path(@message)
    end

    private

    def comment_params
    	params.require(:comment).permit(:content)
    end

    def find_message
    	@message = Message.find(params[:message_id])
    end

    def find_comment
    	@comment = @message.comments.find(params[:id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :find_message, only: [:show, :edit, :update, :destroy]


	def index
		@messages = Message.all.order("created_at DESC")
	end

	def show
	end

	def new
		@message = current_user.messages.build
	end

	def create
		@message = current_user.messages.build(message_params)
		if @message.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
	end

	def destroy
		@message.destroy
		redirect_to root_path
	end

	private

	    def message_params
		    params.require(:message).permit(:title, :description)
	    end

	    def find_message
	    	@message = Message.find(params[:id])
	    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

	<div class="links">
		<% if comment.user_id == current_user.id %>
			<%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
			<%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are you sure?" } %>
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
	<%= f.input :content, label: "Comment" %>
	<%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
  <%= f.input :content, label: "Comment" %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Message Board", root_path, class: "navbar-brand" %>
      </div>
      <ul class="navbar-nav nav">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>  
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <p><%= link_to "New Message", new_message_path, class: "navbar-text navbar-link navbar-right" %></p>
      <% end %>
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
	<%= f.input :title, label:"Message Title" %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end -%>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
	<div class="col-md-4">
		<div class="message">
			<h2 class="message-title"><%= message.title %></h2>
			<%= link_to "View Message", message, class: "btn-custom" %>
		</div>
	</div>
<% end %>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1 class="new-msg-header">New Message</h1>
	<%= render 'form' %>
</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<h2><%= @message.title %></h2>
		<p class="message-posted-by">Posted by <%= @message.user.try(:email) %> <%= time_ago_in_words(@message.created_at) %> ago</p>
		<p class="message-desc"><%= @message.description %></p>
		<!-- Add a Posted By: username at timestamp. -->

		<h3 class="comment-section-header">Comments:</h3>
		<!-- renders the _comment.html.erb partial file. -->
		<p><%= render @message.comments %></p>

		<h3 class="reply-to-msg">Reply to Message:</h3>
		<!-- renders the comments form -->
		<%= render 'comments/form' %>


		<!-- Add a conditional so that the 'edit' and 'destroy' links only appear for the user who created the message. -->
		<div class="links btn-group">
			<%= link_to "Back", root_path, class: "btn btn-default" %>
			<% if @message.user_id == current_user.id %>
				<%= link_to "Edit", edit_message_path(@message), class: "btn btn-default" %>
				<%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
			<% end %>
		</div>
	</div>
</div>